from harmonium.models import Equave, Temperament, TuningSystem, IntervalQuality, Interval, AccidentalSystem, Accidental, AccidentalDirection, NoteName, Note, Clef, Enharmonic, EnharmonicClefPosition, EnharmonicEquivalence, IntervalInverse, EnharmonicIntervalAssignment
from administrarium.models import Administrarion
from django.core.management.base import BaseCommand, CommandError


def make_model(model, acc, ip, **kwargs):
    return model(user_created=acc, user_last_updated=acc, ip_created=ip, ip_last_updated=ip, **kwargs)

def curry_model(acc, ip):
    def inner(model, **kwargs):
        model = make_model(model, acc, ip, **kwargs)
        model.save()
        return model
    return inner

def enh_curry(make_f):
    def inner(cell, elem):
        return make_f(EnharmonicEquivalence, cell=cell, element=elem)
    return inner

def interval_inverse_curry(make_f):
    def inner(interval_1, interval_2):
        first_relation = make_f(IntervalInverse, first_interval=interval_1, second_interval=interval_2)
        second_relation = make_f(IntervalInverse, first_interval=interval_2, second_interval=interval_1)
        return (first_relation, second_relation)
    return inner

def assign_interval_curry(make_f, tuning):
    def inner(note_1, note_2, interval):
        inverse_interval = IntervalInverse.objects.get(first_interval=interval).second_interval
        first_relation = make_f(EnharmonicIntervalAssignment, relative_tuning=tuning, first_note=note_1, second_note=note_2, relative_interval=interval)
        inverse_relation = make_f(EnharmonicIntervalAssignment, relative_tuning=tuning, first_note=note_2, second_note=note_1, relative_interval=inverse_interval)
        return (first_relation, inverse_relation)
    return inner

def do_seed(prime):
    _ip = "127.0.0.1"

    make = curry_model(prime, _ip)
    enh = enh_curry(make)

    octave = make(Equave, name="Octave", ratio=2)
    et = make(Temperament, name="Equal Temperament", has_step_basis=True, has_ratio_basis=False)
    twelve_edo = make(TuningSystem, name="12EDO", chromaticity=12, relative_temperament=et, relative_equave=octave)

    add_interval_inversion = interval_inverse_curry(make)
    assign_twelve_edo_cell_intervals = assign_interval_curry(make, twelve_edo)

    perf_int = make(IntervalQuality, name="Perfect", symbol="P")
    minor_int = make(IntervalQuality, name="Minor", symbol="m")
    major_int = make(IntervalQuality, name="Major", symbol="M")
    dim_int = make(IntervalQuality, name="Diminished", symbol="d")
    dbl_dim_int = make(IntervalQuality, name="Double Diminished", symbol="dd")
    trpl_dim_int = make(IntervalQuality, name="Triple Diminished", symbol="ddd")
    qdrpl_dim_int = make(IntervalQuality, name="Quadruple Diminished", symbol="dddd")
    pntpl_dim_int = make(IntervalQuality, name="Pentuple Diminished", symbol="ddddd")
    aug_int = make(IntervalQuality, name="Augmented", symbol="A")
    dbl_aug_int = make(IntervalQuality, name="Double Augmented", symbol="AA")
    trpl_aug_int = make(IntervalQuality, name="Triple Augmented", symbol="AAA")
    qdrpl_aug_int = make(IntervalQuality, name="Quadruple Augmented", symbol="AAAA")
    pntpl_aug_int = make(IntervalQuality, name="Pentuple Augmented", symbol="AAAAA")

    # THIS WAS ALL METAPROGRAMMED
    P1 = make(Interval, quality=perf_int, symbol='1')
    A1 = make(Interval, quality=aug_int, symbol='1')
    AA1 = make(Interval, quality=dbl_aug_int, symbol='1')
    AAA1 = make(Interval, quality=trpl_aug_int, symbol='1')
    AAAA1 = make(Interval, quality=qdrpl_aug_int, symbol='1')
    d1 = make(Interval, quality=dim_int, symbol='1')
    dd1 = make(Interval, quality=dbl_dim_int, symbol='1')
    ddd1 = make(Interval, quality=trpl_dim_int, symbol='1')
    dddd1 = make(Interval, quality=qdrpl_dim_int, symbol='1')

    M2 = make(Interval, quality=major_int, symbol='2')
    A2 = make(Interval, quality=aug_int, symbol='2')
    AA2 = make(Interval, quality=dbl_aug_int, symbol='2')
    AAA2 = make(Interval, quality=trpl_aug_int, symbol='2')
    AAAA2 = make(Interval, quality=qdrpl_aug_int, symbol='2')
    m2 = make(Interval, quality=minor_int, symbol='2')
    d2 = make(Interval, quality=dim_int, symbol='2')
    dd2 = make(Interval, quality=dbl_dim_int, symbol='2')
    ddd2 = make(Interval, quality=trpl_dim_int, symbol='2')
    dddd2 = make(Interval, quality=qdrpl_dim_int, symbol='2')

    m3 = make(Interval, quality=minor_int, symbol='3')
    M3 = make(Interval, quality=major_int, symbol='3')
    A3 = make(Interval, quality=aug_int, symbol='3')
    AA3 = make(Interval, quality=dbl_aug_int, symbol='3')
    AAA3 = make(Interval, quality=trpl_aug_int, symbol='3')
    d3 = make(Interval, quality=dim_int, symbol='3')
    dd3 = make(Interval, quality=dbl_dim_int, symbol='3')
    ddd3 = make(Interval, quality=trpl_dim_int, symbol='3')
    dddd3 = make(Interval, quality=qdrpl_dim_int, symbol='3')
    AAAA3 = make(Interval, quality=qdrpl_aug_int, symbol='3')

    P4 = make(Interval, quality=perf_int, symbol='4')
    A4 = make(Interval, quality=aug_int, symbol='4')
    AA4 = make(Interval, quality=dbl_aug_int, symbol='4')
    AAA4 = make(Interval, quality=trpl_aug_int, symbol='4')
    AAAA4 = make(Interval, quality=qdrpl_aug_int, symbol='4')
    d4 = make(Interval, quality=dim_int, symbol='4')
    dd4 = make(Interval, quality=dbl_dim_int, symbol='4')
    ddd4 = make(Interval, quality=trpl_dim_int, symbol='4')
    dddd4 = make(Interval, quality=qdrpl_dim_int, symbol='4')
    AAAAA4 = make(Interval, quality=pntpl_aug_int, symbol='4')

    P5 = make(Interval, quality=perf_int, symbol='5')
    A5 = make(Interval, quality=aug_int, symbol='5')
    AA5 = make(Interval, quality=dbl_aug_int, symbol='5')
    AAA5 = make(Interval, quality=trpl_aug_int, symbol='5')
    AAAA5 = make(Interval, quality=qdrpl_aug_int, symbol='5')
    d5 = make(Interval, quality=dim_int, symbol='5')
    dd5 = make(Interval, quality=dbl_dim_int, symbol='5')
    ddd5 = make(Interval, quality=trpl_dim_int, symbol='5')
    dddd5 = make(Interval, quality=qdrpl_dim_int, symbol='5')
    ddddd5 = make(Interval, quality=pntpl_dim_int, symbol='5')

    m6 = make(Interval, quality=minor_int, symbol='6')
    M6 = make(Interval, quality=major_int, symbol='6')
    A6 = make(Interval, quality=aug_int, symbol='6')
    AA6 = make(Interval, quality=dbl_aug_int, symbol='6')
    AAA6 = make(Interval, quality=trpl_aug_int, symbol='6')
    d6 = make(Interval, quality=dim_int, symbol='6')
    dd6 = make(Interval, quality=dbl_dim_int, symbol='6')
    ddd6 = make(Interval, quality=trpl_dim_int, symbol='6')
    dddd6 = make(Interval, quality=qdrpl_dim_int, symbol='6')
    AAAA6 = make(Interval, quality=qdrpl_aug_int, symbol='6')

    m7 = make(Interval, quality=minor_int, symbol='7')
    M7 = make(Interval, quality=major_int, symbol='7')
    A7 = make(Interval, quality=aug_int, symbol='7')
    AA7 = make(Interval, quality=dbl_aug_int, symbol='7')
    AAA7 = make(Interval, quality=trpl_aug_int, symbol='7')
    d7 = make(Interval, quality=dim_int, symbol='7')
    dd7 = make(Interval, quality=dbl_dim_int, symbol='7')
    ddd7 = make(Interval, quality=trpl_dim_int, symbol='7')
    dddd7 = make(Interval, quality=qdrpl_dim_int, symbol='7')
    AAAA7 = make(Interval, quality=qdrpl_aug_int, symbol='7')

    P8 = make(Interval, quality=perf_int, symbol='8')
    A8 = make(Interval, quality=aug_int, symbol='8')
    AA8 = make(Interval, quality=dbl_aug_int, symbol='8')
    AAA8 = make(Interval, quality=trpl_aug_int, symbol='8')
    AAAA8 = make(Interval, quality=qdrpl_aug_int, symbol='8')
    d8 = make(Interval, quality=dim_int, symbol='8')
    dd8 = make(Interval, quality=dbl_dim_int, symbol='8')
    ddd8 = make(Interval, quality=trpl_dim_int, symbol='8')
    dddd8 = make(Interval, quality=qdrpl_dim_int, symbol='8')

    add_interval_inversion(M2, m7)
    add_interval_inversion(A2, d7)
    add_interval_inversion(AA2, dd7)
    add_interval_inversion(AAA2, ddd7)
    add_interval_inversion(AAAA2, dddd7)
    add_interval_inversion(m3, M6)
    add_interval_inversion(M3, m6)
    add_interval_inversion(A3, d6)
    add_interval_inversion(AA3, dd6)
    add_interval_inversion(AAA3, ddd6)
    add_interval_inversion(P4, P5)
    add_interval_inversion(A4, d5)
    add_interval_inversion(AA4, dd5)
    add_interval_inversion(AAA4, ddd5)
    add_interval_inversion(AAAA4, dddd5)
    add_interval_inversion(A5, d4)
    add_interval_inversion(AA5, dd4)
    add_interval_inversion(AAA5, ddd4)
    add_interval_inversion(AAAA5, dddd4)
    add_interval_inversion(A6, d3)
    add_interval_inversion(AA6, dd3)
    add_interval_inversion(AAA6, ddd3)
    add_interval_inversion(M7, m2)
    add_interval_inversion(A7, d2)
    add_interval_inversion(AA7, dd2)
    add_interval_inversion(AAA7, ddd2)
    add_interval_inversion(dddd3, AAAA6)
    add_interval_inversion(dddd6, AAAA3)
    add_interval_inversion(dddd2, AAAA7)
    add_interval_inversion(ddddd5, AAAAA4)
    add_interval_inversion(P8, P1)
    add_interval_inversion(A8, d1)
    add_interval_inversion(AA8, dd1)
    add_interval_inversion(AAA8, ddd1)
    add_interval_inversion(AAAA8, dddd1)
    add_interval_inversion(A1, d8)
    add_interval_inversion(AA1, dd8)
    add_interval_inversion(AAA1, ddd8)
    add_interval_inversion(AAAA1, dddd8)
    # END METAPROGRAMMING

    comprac = make(AccidentalSystem, name="Common Practice")
    upward = make(AccidentalDirection, name="Upward")
    downward = make(AccidentalDirection, name="Downward")

    nat = make(Accidental, name="Natural", symbol="♮", interval_mod=P1, direction=upward, accidental_system=comprac)
    sharp = make(Accidental, name="Sharp", symbol="#", interval_mod=m2, direction=upward, accidental_system=comprac)
    double_sharp = make(Accidental, name="Double Sharp", symbol="##", interval_mod=M2, direction=upward, accidental_system=comprac)
    flat = make(Accidental, name="Flat", symbol="b", interval_mod=m2, direction=downward, accidental_system=comprac)
    double_flat = make(Accidental, name="Double Flat", symbol="bb", interval_mod=M2, direction=downward, accidental_system=comprac)

    a = make(NoteName, name="A")
    b = make(NoteName, name="B")
    c = make(NoteName, name="C")
    d = make(NoteName, name="D")
    e = make(NoteName, name="E")
    f = make(NoteName, name="F")
    g = make(NoteName, name="G")

    a_nat = make(Note, note_name=a, relative_accidental=nat, tuning_system=twelve_edo)
    a_sharp = make(Note, note_name=a, relative_accidental=sharp, tuning_system=twelve_edo)
    a_flat = make(Note, note_name=a, relative_accidental=flat, tuning_system=twelve_edo)
    a_dblsharp = make(Note, note_name=a, relative_accidental=double_sharp, tuning_system=twelve_edo)
    a_dblflat = make(Note, note_name=a, relative_accidental=double_flat, tuning_system=twelve_edo)

    b_nat = make(Note, note_name=b, relative_accidental=nat, tuning_system=twelve_edo)
    b_sharp = make(Note, note_name=b, relative_accidental=sharp, tuning_system=twelve_edo)
    b_flat = make(Note, note_name=b, relative_accidental=flat, tuning_system=twelve_edo)
    b_dblsharp = make(Note, note_name=b, relative_accidental=double_sharp, tuning_system=twelve_edo)
    b_dblflat = make(Note, note_name=b, relative_accidental=double_flat, tuning_system=twelve_edo)

    c_nat = make(Note, note_name=c, relative_accidental=nat, tuning_system=twelve_edo)
    c_sharp = make(Note, note_name=c, relative_accidental=sharp, tuning_system=twelve_edo)
    c_flat = make(Note, note_name=c, relative_accidental=flat, tuning_system=twelve_edo)
    c_dblsharp = make(Note, note_name=c, relative_accidental=double_sharp, tuning_system=twelve_edo)
    c_dblflat = make(Note, note_name=c, relative_accidental=double_flat, tuning_system=twelve_edo)

    d_nat = make(Note, note_name=d, relative_accidental=nat, tuning_system=twelve_edo)
    d_sharp = make(Note, note_name=d, relative_accidental=sharp, tuning_system=twelve_edo)
    d_flat = make(Note, note_name=d, relative_accidental=flat, tuning_system=twelve_edo)
    d_dblsharp = make(Note, note_name=d, relative_accidental=double_sharp, tuning_system=twelve_edo)
    d_dblflat = make(Note, note_name=d, relative_accidental=double_flat, tuning_system=twelve_edo)

    e_nat = make(Note, note_name=e, relative_accidental=nat, tuning_system=twelve_edo)
    e_sharp = make(Note, note_name=e, relative_accidental=sharp, tuning_system=twelve_edo)
    e_flat = make(Note, note_name=e, relative_accidental=flat, tuning_system=twelve_edo)
    e_dblsharp = make(Note, note_name=e, relative_accidental=double_sharp, tuning_system=twelve_edo)
    e_dblflat = make(Note, note_name=e, relative_accidental=double_flat, tuning_system=twelve_edo)

    f_nat = make(Note, note_name=f, relative_accidental=nat, tuning_system=twelve_edo)
    f_sharp = make(Note, note_name=f, relative_accidental=sharp, tuning_system=twelve_edo)
    f_flat = make(Note, note_name=f, relative_accidental=flat, tuning_system=twelve_edo)
    f_dblsharp = make(Note, note_name=f, relative_accidental=double_sharp, tuning_system=twelve_edo)
    f_dblflat = make(Note, note_name=f, relative_accidental=double_flat, tuning_system=twelve_edo)

    g_nat = make(Note, note_name=g, relative_accidental=nat, tuning_system=twelve_edo)
    g_sharp = make(Note, note_name=g, relative_accidental=sharp, tuning_system=twelve_edo)
    g_flat = make(Note, note_name=g, relative_accidental=flat, tuning_system=twelve_edo)
    g_dblsharp = make(Note, note_name=g, relative_accidental=double_sharp, tuning_system=twelve_edo)
    g_dblflat = make(Note, note_name=g, relative_accidental=double_flat, tuning_system=twelve_edo)

    # THIS WAS ALL METAPROGRAMMED
    assign_twelve_edo_cell_intervals(a_flat, a_dblflat, d1)
    assign_twelve_edo_cell_intervals(a_nat, a_dblflat, dd1)
    assign_twelve_edo_cell_intervals(a_nat, a_flat, d1)
    assign_twelve_edo_cell_intervals(a_sharp, a_dblflat, ddd1)
    assign_twelve_edo_cell_intervals(a_sharp, a_flat, dd1)
    assign_twelve_edo_cell_intervals(a_sharp, a_nat, d1)
    assign_twelve_edo_cell_intervals(a_dblsharp, a_dblflat, dddd1)
    assign_twelve_edo_cell_intervals(a_dblsharp, a_flat, ddd1)
    assign_twelve_edo_cell_intervals(a_dblsharp, a_nat, dd1)
    assign_twelve_edo_cell_intervals(a_dblsharp, a_sharp, d1)
    assign_twelve_edo_cell_intervals(b_dblflat, a_dblflat, m7)
    assign_twelve_edo_cell_intervals(b_dblflat, a_flat, M7)
    assign_twelve_edo_cell_intervals(b_dblflat, a_nat, A7)
    assign_twelve_edo_cell_intervals(b_dblflat, a_sharp, AA7)
    assign_twelve_edo_cell_intervals(b_dblflat, a_dblsharp, AAA7)
    assign_twelve_edo_cell_intervals(b_nat, a_dblflat, d7)
    assign_twelve_edo_cell_intervals(b_nat, a_flat, m7)
    assign_twelve_edo_cell_intervals(b_nat, a_nat, M7)
    assign_twelve_edo_cell_intervals(b_nat, a_sharp, A7)
    assign_twelve_edo_cell_intervals(b_nat, a_dblsharp, AA7)
    assign_twelve_edo_cell_intervals(b_nat, b_dblflat, d1)
    assign_twelve_edo_cell_intervals(b_nat, a_dblflat, dd7)
    assign_twelve_edo_cell_intervals(b_nat, a_flat, d7)
    assign_twelve_edo_cell_intervals(b_nat, a_nat, m7)
    assign_twelve_edo_cell_intervals(b_nat, a_sharp, M7)
    assign_twelve_edo_cell_intervals(b_nat, a_dblsharp, A7)
    assign_twelve_edo_cell_intervals(b_nat, b_dblflat, dd1)
    assign_twelve_edo_cell_intervals(b_nat, b_nat, d1)
    assign_twelve_edo_cell_intervals(b_sharp, a_dblflat, ddd7)
    assign_twelve_edo_cell_intervals(b_sharp, a_flat, dd7)
    assign_twelve_edo_cell_intervals(b_sharp, a_nat, d7)
    assign_twelve_edo_cell_intervals(b_sharp, a_sharp, m7)
    assign_twelve_edo_cell_intervals(b_sharp, a_dblsharp, M7)
    assign_twelve_edo_cell_intervals(b_sharp, b_dblflat, ddd1)
    assign_twelve_edo_cell_intervals(b_sharp, b_nat, dd1)
    assign_twelve_edo_cell_intervals(b_sharp, b_nat, d1)
    assign_twelve_edo_cell_intervals(b_dblsharp, a_dblflat, dddd7)
    assign_twelve_edo_cell_intervals(b_dblsharp, a_flat, ddd7)
    assign_twelve_edo_cell_intervals(b_dblsharp, a_nat, dd7)
    assign_twelve_edo_cell_intervals(b_dblsharp, a_sharp, d7)
    assign_twelve_edo_cell_intervals(b_dblsharp, a_dblsharp, m7)
    assign_twelve_edo_cell_intervals(b_dblsharp, b_dblflat, dddd1)
    assign_twelve_edo_cell_intervals(b_dblsharp, b_nat, ddd1)
    assign_twelve_edo_cell_intervals(b_dblsharp, b_nat, dd1)
    assign_twelve_edo_cell_intervals(b_dblsharp, b_sharp, d1)
    assign_twelve_edo_cell_intervals(c_dblflat, a_dblflat, M6)
    assign_twelve_edo_cell_intervals(c_dblflat, a_flat, A6)
    assign_twelve_edo_cell_intervals(c_dblflat, a_nat, AA6)
    assign_twelve_edo_cell_intervals(c_dblflat, a_sharp, AAA6)
    assign_twelve_edo_cell_intervals(c_dblflat, a_dblsharp, AAAA6)
    assign_twelve_edo_cell_intervals(c_dblflat, b_dblflat, M7)
    assign_twelve_edo_cell_intervals(c_dblflat, b_nat, A7)
    assign_twelve_edo_cell_intervals(c_dblflat, b_nat, AA7)
    assign_twelve_edo_cell_intervals(c_dblflat, b_sharp, AAA7)
    assign_twelve_edo_cell_intervals(c_dblflat, b_dblsharp, AAAA7)
    assign_twelve_edo_cell_intervals(c_flat, a_dblflat, m6)
    assign_twelve_edo_cell_intervals(c_flat, a_flat, M6)
    assign_twelve_edo_cell_intervals(c_flat, a_nat, A6)
    assign_twelve_edo_cell_intervals(c_flat, a_sharp, AA6)
    assign_twelve_edo_cell_intervals(c_flat, a_dblsharp, AAA6)
    assign_twelve_edo_cell_intervals(c_flat, b_dblflat, m7)
    assign_twelve_edo_cell_intervals(c_flat, b_nat, M7)
    assign_twelve_edo_cell_intervals(c_flat, b_nat, A7)
    assign_twelve_edo_cell_intervals(c_flat, b_sharp, AA7)
    assign_twelve_edo_cell_intervals(c_flat, b_dblsharp, AAA7)
    assign_twelve_edo_cell_intervals(c_flat, c_dblflat, d1)
    assign_twelve_edo_cell_intervals(c_nat, a_dblflat, d6)
    assign_twelve_edo_cell_intervals(c_nat, a_flat, m6)
    assign_twelve_edo_cell_intervals(c_nat, a_nat, M6)
    assign_twelve_edo_cell_intervals(c_nat, a_sharp, A6)
    assign_twelve_edo_cell_intervals(c_nat, a_dblsharp, AA6)
    assign_twelve_edo_cell_intervals(c_nat, b_dblflat, d7)
    assign_twelve_edo_cell_intervals(c_nat, b_nat, m7)
    assign_twelve_edo_cell_intervals(c_nat, b_nat, M7)
    assign_twelve_edo_cell_intervals(c_nat, b_sharp, A7)
    assign_twelve_edo_cell_intervals(c_nat, b_dblsharp, AA7)
    assign_twelve_edo_cell_intervals(c_nat, c_dblflat, dd1)
    assign_twelve_edo_cell_intervals(c_nat, c_flat, d1)
    assign_twelve_edo_cell_intervals(c_sharp, a_dblflat, dd6)
    assign_twelve_edo_cell_intervals(c_sharp, a_flat, d6)
    assign_twelve_edo_cell_intervals(c_sharp, a_nat, m6)
    assign_twelve_edo_cell_intervals(c_sharp, a_sharp, M6)
    assign_twelve_edo_cell_intervals(c_sharp, a_dblsharp, A6)
    assign_twelve_edo_cell_intervals(c_sharp, b_dblflat, dd7)
    assign_twelve_edo_cell_intervals(c_sharp, b_nat, d7)
    assign_twelve_edo_cell_intervals(c_sharp, b_nat, m7)
    assign_twelve_edo_cell_intervals(c_sharp, b_sharp, M7)
    assign_twelve_edo_cell_intervals(c_sharp, b_dblsharp, A7)
    assign_twelve_edo_cell_intervals(c_sharp, c_dblflat, ddd1)
    assign_twelve_edo_cell_intervals(c_sharp, c_flat, dd1)
    assign_twelve_edo_cell_intervals(c_sharp, c_nat, d1)
    assign_twelve_edo_cell_intervals(c_dblsharp, a_dblflat, ddd6)
    assign_twelve_edo_cell_intervals(c_dblsharp, a_flat, dd6)
    assign_twelve_edo_cell_intervals(c_dblsharp, a_nat, d6)
    assign_twelve_edo_cell_intervals(c_dblsharp, a_sharp, m6)
    assign_twelve_edo_cell_intervals(c_dblsharp, a_dblsharp, M6)
    assign_twelve_edo_cell_intervals(c_dblsharp, b_dblflat, ddd7)
    assign_twelve_edo_cell_intervals(c_dblsharp, b_nat, dd7)
    assign_twelve_edo_cell_intervals(c_dblsharp, b_nat, d7)
    assign_twelve_edo_cell_intervals(c_dblsharp, b_sharp, m7)
    assign_twelve_edo_cell_intervals(c_dblsharp, b_dblsharp, M7)
    assign_twelve_edo_cell_intervals(c_dblsharp, c_dblflat, dddd1)
    assign_twelve_edo_cell_intervals(c_dblsharp, c_flat, ddd1)
    assign_twelve_edo_cell_intervals(c_dblsharp, c_nat, dd1)
    assign_twelve_edo_cell_intervals(c_dblsharp, c_sharp, d1)
    assign_twelve_edo_cell_intervals(d_dblflat, a_dblflat, P5)
    assign_twelve_edo_cell_intervals(d_dblflat, a_flat, A5)
    assign_twelve_edo_cell_intervals(d_dblflat, a_nat, AA5)
    assign_twelve_edo_cell_intervals(d_dblflat, a_sharp, AAA5)
    assign_twelve_edo_cell_intervals(d_dblflat, a_dblsharp, AAAA5)
    assign_twelve_edo_cell_intervals(d_dblflat, b_dblflat, M6)
    assign_twelve_edo_cell_intervals(d_dblflat, b_nat, A6)
    assign_twelve_edo_cell_intervals(d_dblflat, b_nat, AA6)
    assign_twelve_edo_cell_intervals(d_dblflat, b_sharp, AAA6)
    assign_twelve_edo_cell_intervals(d_dblflat, b_dblsharp, AAAA6)
    assign_twelve_edo_cell_intervals(d_dblflat, c_dblflat, m7)
    assign_twelve_edo_cell_intervals(d_dblflat, c_flat, M7)
    assign_twelve_edo_cell_intervals(d_dblflat, c_nat, A7)
    assign_twelve_edo_cell_intervals(d_dblflat, c_sharp, AA7)
    assign_twelve_edo_cell_intervals(d_dblflat, c_dblsharp, AAA7)
    assign_twelve_edo_cell_intervals(d_flat, a_dblflat, d5)
    assign_twelve_edo_cell_intervals(d_flat, a_flat, P5)
    assign_twelve_edo_cell_intervals(d_flat, a_nat, A5)
    assign_twelve_edo_cell_intervals(d_flat, a_sharp, AA5)
    assign_twelve_edo_cell_intervals(d_flat, a_dblsharp, AAA5)
    assign_twelve_edo_cell_intervals(d_flat, b_dblflat, m6)
    assign_twelve_edo_cell_intervals(d_flat, b_nat, M6)
    assign_twelve_edo_cell_intervals(d_flat, b_nat, A6)
    assign_twelve_edo_cell_intervals(d_flat, b_sharp, AA6)
    assign_twelve_edo_cell_intervals(d_flat, b_dblsharp, AAA6)
    assign_twelve_edo_cell_intervals(d_flat, c_dblflat, d7)
    assign_twelve_edo_cell_intervals(d_flat, c_flat, m7)
    assign_twelve_edo_cell_intervals(d_flat, c_nat, M7)
    assign_twelve_edo_cell_intervals(d_flat, c_sharp, A7)
    assign_twelve_edo_cell_intervals(d_flat, c_dblsharp, AA7)
    assign_twelve_edo_cell_intervals(d_flat, d_dblflat, d1)
    assign_twelve_edo_cell_intervals(d_nat, a_dblflat, dd5)
    assign_twelve_edo_cell_intervals(d_nat, a_flat, d5)
    assign_twelve_edo_cell_intervals(d_nat, a_nat, P5)
    assign_twelve_edo_cell_intervals(d_nat, a_sharp, A5)
    assign_twelve_edo_cell_intervals(d_nat, a_dblsharp, AA5)
    assign_twelve_edo_cell_intervals(d_nat, b_dblflat, d6)
    assign_twelve_edo_cell_intervals(d_nat, b_nat, m6)
    assign_twelve_edo_cell_intervals(d_nat, b_nat, M6)
    assign_twelve_edo_cell_intervals(d_nat, b_sharp, A6)
    assign_twelve_edo_cell_intervals(d_nat, b_dblsharp, AA6)
    assign_twelve_edo_cell_intervals(d_nat, c_dblflat, dd7)
    assign_twelve_edo_cell_intervals(d_nat, c_flat, d7)
    assign_twelve_edo_cell_intervals(d_nat, c_nat, m7)
    assign_twelve_edo_cell_intervals(d_nat, c_sharp, M7)
    assign_twelve_edo_cell_intervals(d_nat, c_dblsharp, A7)
    assign_twelve_edo_cell_intervals(d_nat, d_dblflat, dd1)
    assign_twelve_edo_cell_intervals(d_nat, d_flat, d1)
    assign_twelve_edo_cell_intervals(d_sharp, a_dblflat, ddd5)
    assign_twelve_edo_cell_intervals(d_sharp, a_flat, dd5)
    assign_twelve_edo_cell_intervals(d_sharp, a_nat, d5)
    assign_twelve_edo_cell_intervals(d_sharp, a_sharp, P5)
    assign_twelve_edo_cell_intervals(d_sharp, a_dblsharp, A5)
    assign_twelve_edo_cell_intervals(d_sharp, b_dblflat, dd6)
    assign_twelve_edo_cell_intervals(d_sharp, b_nat, d6)
    assign_twelve_edo_cell_intervals(d_sharp, b_nat, m6)
    assign_twelve_edo_cell_intervals(d_sharp, b_sharp, M6)
    assign_twelve_edo_cell_intervals(d_sharp, b_dblsharp, A6)
    assign_twelve_edo_cell_intervals(d_sharp, c_dblflat, ddd7)
    assign_twelve_edo_cell_intervals(d_sharp, c_flat, dd7)
    assign_twelve_edo_cell_intervals(d_sharp, c_nat, d7)
    assign_twelve_edo_cell_intervals(d_sharp, c_sharp, m7)
    assign_twelve_edo_cell_intervals(d_sharp, c_dblsharp, M7)
    assign_twelve_edo_cell_intervals(d_sharp, d_dblflat, ddd1)
    assign_twelve_edo_cell_intervals(d_sharp, d_flat, dd1)
    assign_twelve_edo_cell_intervals(d_sharp, d_nat, d1)
    assign_twelve_edo_cell_intervals(d_dblsharp, a_dblflat, dddd5)
    assign_twelve_edo_cell_intervals(d_dblsharp, a_flat, ddd5)
    assign_twelve_edo_cell_intervals(d_dblsharp, a_nat, dd5)
    assign_twelve_edo_cell_intervals(d_dblsharp, a_sharp, d5)
    assign_twelve_edo_cell_intervals(d_dblsharp, a_dblsharp, P5)
    assign_twelve_edo_cell_intervals(d_dblsharp, b_dblflat, ddd6)
    assign_twelve_edo_cell_intervals(d_dblsharp, b_nat, dd6)
    assign_twelve_edo_cell_intervals(d_dblsharp, b_nat, d6)
    assign_twelve_edo_cell_intervals(d_dblsharp, b_sharp, m6)
    assign_twelve_edo_cell_intervals(d_dblsharp, b_dblsharp, M6)
    assign_twelve_edo_cell_intervals(d_dblsharp, c_dblflat, dddd7)
    assign_twelve_edo_cell_intervals(d_dblsharp, c_flat, ddd7)
    assign_twelve_edo_cell_intervals(d_dblsharp, c_nat, dd7)
    assign_twelve_edo_cell_intervals(d_dblsharp, c_sharp, d7)
    assign_twelve_edo_cell_intervals(d_dblsharp, c_dblsharp, m7)
    assign_twelve_edo_cell_intervals(d_dblsharp, d_dblflat, dddd1)
    assign_twelve_edo_cell_intervals(d_dblsharp, d_flat, ddd1)
    assign_twelve_edo_cell_intervals(d_dblsharp, d_nat, dd1)
    assign_twelve_edo_cell_intervals(d_dblsharp, d_sharp, d1)
    assign_twelve_edo_cell_intervals(e_dblflat, a_dblflat, P4)
    assign_twelve_edo_cell_intervals(e_dblflat, a_flat, A4)
    assign_twelve_edo_cell_intervals(e_dblflat, a_nat, AA4)
    assign_twelve_edo_cell_intervals(e_dblflat, a_sharp, AAA4)
    assign_twelve_edo_cell_intervals(e_dblflat, a_dblsharp, AAAA4)
    assign_twelve_edo_cell_intervals(e_dblflat, b_dblflat, P5)
    assign_twelve_edo_cell_intervals(e_dblflat, b_nat, A5)
    assign_twelve_edo_cell_intervals(e_dblflat, b_nat, AA5)
    assign_twelve_edo_cell_intervals(e_dblflat, b_sharp, AAA5)
    assign_twelve_edo_cell_intervals(e_dblflat, b_dblsharp, AAAA5)
    assign_twelve_edo_cell_intervals(e_dblflat, c_dblflat, m6)
    assign_twelve_edo_cell_intervals(e_dblflat, c_flat, M6)
    assign_twelve_edo_cell_intervals(e_dblflat, c_nat, A6)
    assign_twelve_edo_cell_intervals(e_dblflat, c_sharp, AA6)
    assign_twelve_edo_cell_intervals(e_dblflat, c_dblsharp, AAA6)
    assign_twelve_edo_cell_intervals(e_dblflat, d_dblflat, m7)
    assign_twelve_edo_cell_intervals(e_dblflat, d_flat, M7)
    assign_twelve_edo_cell_intervals(e_dblflat, d_nat, A7)
    assign_twelve_edo_cell_intervals(e_dblflat, d_sharp, AA7)
    assign_twelve_edo_cell_intervals(e_dblflat, d_dblsharp, AAA7)
    assign_twelve_edo_cell_intervals(e_flat, a_dblflat, d4)
    assign_twelve_edo_cell_intervals(e_flat, a_flat, P4)
    assign_twelve_edo_cell_intervals(e_flat, a_nat, A4)
    assign_twelve_edo_cell_intervals(e_flat, a_sharp, AA4)
    assign_twelve_edo_cell_intervals(e_flat, a_dblsharp, AAA4)
    assign_twelve_edo_cell_intervals(e_flat, b_dblflat, d5)
    assign_twelve_edo_cell_intervals(e_flat, b_nat, P5)
    assign_twelve_edo_cell_intervals(e_flat, b_nat, A5)
    assign_twelve_edo_cell_intervals(e_flat, b_sharp, AA5)
    assign_twelve_edo_cell_intervals(e_flat, b_dblsharp, AAA5)
    assign_twelve_edo_cell_intervals(e_flat, c_dblflat, d6)
    assign_twelve_edo_cell_intervals(e_flat, c_flat, m6)
    assign_twelve_edo_cell_intervals(e_flat, c_nat, M6)
    assign_twelve_edo_cell_intervals(e_flat, c_sharp, A6)
    assign_twelve_edo_cell_intervals(e_flat, c_dblsharp, AA6)
    assign_twelve_edo_cell_intervals(e_flat, d_dblflat, d7)
    assign_twelve_edo_cell_intervals(e_flat, d_flat, m7)
    assign_twelve_edo_cell_intervals(e_flat, d_nat, M7)
    assign_twelve_edo_cell_intervals(e_flat, d_sharp, A7)
    assign_twelve_edo_cell_intervals(e_flat, d_dblsharp, AA7)
    assign_twelve_edo_cell_intervals(e_flat, e_dblflat, d1)
    assign_twelve_edo_cell_intervals(e_nat, a_dblflat, dd4)
    assign_twelve_edo_cell_intervals(e_nat, a_flat, d4)
    assign_twelve_edo_cell_intervals(e_nat, a_nat, P4)
    assign_twelve_edo_cell_intervals(e_nat, a_sharp, A4)
    assign_twelve_edo_cell_intervals(e_nat, a_dblsharp, AA4)
    assign_twelve_edo_cell_intervals(e_nat, b_dblflat, dd5)
    assign_twelve_edo_cell_intervals(e_nat, b_nat, d5)
    assign_twelve_edo_cell_intervals(e_nat, b_nat, P5)
    assign_twelve_edo_cell_intervals(e_nat, b_sharp, A5)
    assign_twelve_edo_cell_intervals(e_nat, b_dblsharp, AA5)
    assign_twelve_edo_cell_intervals(e_nat, c_dblflat, dd6)
    assign_twelve_edo_cell_intervals(e_nat, c_flat, d6)
    assign_twelve_edo_cell_intervals(e_nat, c_nat, m6)
    assign_twelve_edo_cell_intervals(e_nat, c_sharp, M6)
    assign_twelve_edo_cell_intervals(e_nat, c_dblsharp, A6)
    assign_twelve_edo_cell_intervals(e_nat, d_dblflat, dd7)
    assign_twelve_edo_cell_intervals(e_nat, d_flat, d7)
    assign_twelve_edo_cell_intervals(e_nat, d_nat, m7)
    assign_twelve_edo_cell_intervals(e_nat, d_sharp, M7)
    assign_twelve_edo_cell_intervals(e_nat, d_dblsharp, A7)
    assign_twelve_edo_cell_intervals(e_nat, e_dblflat, dd1)
    assign_twelve_edo_cell_intervals(e_nat, e_flat, d1)
    assign_twelve_edo_cell_intervals(e_sharp, a_dblflat, ddd4)
    assign_twelve_edo_cell_intervals(e_sharp, a_flat, ddd4)
    assign_twelve_edo_cell_intervals(e_sharp, a_nat, dd4)
    assign_twelve_edo_cell_intervals(e_sharp, a_sharp, P4)
    assign_twelve_edo_cell_intervals(e_sharp, a_dblsharp, A4)
    assign_twelve_edo_cell_intervals(e_sharp, b_dblflat, ddd5)
    assign_twelve_edo_cell_intervals(e_sharp, b_nat, dd5)
    assign_twelve_edo_cell_intervals(e_sharp, b_nat, d5)
    assign_twelve_edo_cell_intervals(e_sharp, b_sharp, P5)
    assign_twelve_edo_cell_intervals(e_sharp, b_dblsharp, A5)
    assign_twelve_edo_cell_intervals(e_sharp, c_dblflat, ddd6)
    assign_twelve_edo_cell_intervals(e_sharp, c_flat, dd6)
    assign_twelve_edo_cell_intervals(e_sharp, c_nat, d6)
    assign_twelve_edo_cell_intervals(e_sharp, c_sharp, m6)
    assign_twelve_edo_cell_intervals(e_sharp, c_dblsharp, M6)
    assign_twelve_edo_cell_intervals(e_sharp, d_dblflat, ddd7)
    assign_twelve_edo_cell_intervals(e_sharp, d_flat, dd7)
    assign_twelve_edo_cell_intervals(e_sharp, d_nat, d7)
    assign_twelve_edo_cell_intervals(e_sharp, d_sharp, m7)
    assign_twelve_edo_cell_intervals(e_sharp, d_dblsharp, M7)
    assign_twelve_edo_cell_intervals(e_sharp, e_dblflat, ddd1)
    assign_twelve_edo_cell_intervals(e_sharp, e_flat, dd1)
    assign_twelve_edo_cell_intervals(e_sharp, e_nat, d1)
    assign_twelve_edo_cell_intervals(e_dblsharp, a_dblflat, dddd4)
    assign_twelve_edo_cell_intervals(e_dblsharp, a_flat, ddd4)
    assign_twelve_edo_cell_intervals(e_dblsharp, a_nat, dd4)
    assign_twelve_edo_cell_intervals(e_dblsharp, a_sharp, d4)
    assign_twelve_edo_cell_intervals(e_dblsharp, a_dblsharp, P4)
    assign_twelve_edo_cell_intervals(e_dblsharp, b_dblflat, dddd5)
    assign_twelve_edo_cell_intervals(e_dblsharp, b_nat, ddd5)
    assign_twelve_edo_cell_intervals(e_dblsharp, b_nat, dd5)
    assign_twelve_edo_cell_intervals(e_dblsharp, b_sharp, d5)
    assign_twelve_edo_cell_intervals(e_dblsharp, b_dblsharp, P5)
    assign_twelve_edo_cell_intervals(e_dblsharp, c_dblflat, dddd6)
    assign_twelve_edo_cell_intervals(e_dblsharp, c_flat, ddd6)
    assign_twelve_edo_cell_intervals(e_dblsharp, c_nat, dd6)
    assign_twelve_edo_cell_intervals(e_dblsharp, c_sharp, d6)
    assign_twelve_edo_cell_intervals(e_dblsharp, c_dblsharp, m6)
    assign_twelve_edo_cell_intervals(e_dblsharp, d_dblflat, dddd7)
    assign_twelve_edo_cell_intervals(e_dblsharp, d_flat, ddd7)
    assign_twelve_edo_cell_intervals(e_dblsharp, d_nat, dd7)
    assign_twelve_edo_cell_intervals(e_dblsharp, d_sharp, d7)
    assign_twelve_edo_cell_intervals(e_dblsharp, d_dblsharp, m7)
    assign_twelve_edo_cell_intervals(e_dblsharp, e_dblflat, dddd1)
    assign_twelve_edo_cell_intervals(e_dblsharp, e_flat, ddd1)
    assign_twelve_edo_cell_intervals(e_dblsharp, e_nat, dd1)
    assign_twelve_edo_cell_intervals(e_dblsharp, e_sharp, d1)
    assign_twelve_edo_cell_intervals(f_dblflat, a_dblflat, M3)
    assign_twelve_edo_cell_intervals(f_dblflat, a_flat, A3)
    assign_twelve_edo_cell_intervals(f_dblflat, a_nat, AA3)
    assign_twelve_edo_cell_intervals(f_dblflat, a_sharp, AAA3)
    assign_twelve_edo_cell_intervals(f_dblflat, a_dblsharp, AAAA3)
    assign_twelve_edo_cell_intervals(f_dblflat, b_dblflat, A4)
    assign_twelve_edo_cell_intervals(f_dblflat, b_nat, AA4)
    assign_twelve_edo_cell_intervals(f_dblflat, b_nat, AAA4)
    assign_twelve_edo_cell_intervals(f_dblflat, b_sharp, AAAA4)
    assign_twelve_edo_cell_intervals(f_dblflat, b_dblsharp, AAAAA4)
    assign_twelve_edo_cell_intervals(f_dblflat, c_dblflat, P5)
    assign_twelve_edo_cell_intervals(f_dblflat, c_flat, A5)
    assign_twelve_edo_cell_intervals(f_dblflat, c_nat, AA5)
    assign_twelve_edo_cell_intervals(f_dblflat, c_sharp, AAA5)
    assign_twelve_edo_cell_intervals(f_dblflat, c_dblsharp, AAAA5)
    assign_twelve_edo_cell_intervals(f_dblflat, d_dblflat, M6)
    assign_twelve_edo_cell_intervals(f_dblflat, d_flat, A6)
    assign_twelve_edo_cell_intervals(f_dblflat, d_nat, AA6)
    assign_twelve_edo_cell_intervals(f_dblflat, d_sharp, AAA6)
    assign_twelve_edo_cell_intervals(f_dblflat, d_dblsharp, AAAA6)
    assign_twelve_edo_cell_intervals(f_dblflat, e_dblflat, M7)
    assign_twelve_edo_cell_intervals(f_dblflat, e_flat, A7)
    assign_twelve_edo_cell_intervals(f_dblflat, e_nat, AA7)
    assign_twelve_edo_cell_intervals(f_dblflat, e_sharp, AAA7)
    assign_twelve_edo_cell_intervals(f_dblflat, e_dblsharp, AAAA7)
    assign_twelve_edo_cell_intervals(f_flat, a_dblflat, m3)
    assign_twelve_edo_cell_intervals(f_flat, a_flat, M3)
    assign_twelve_edo_cell_intervals(f_flat, a_nat, A3)
    assign_twelve_edo_cell_intervals(f_flat, a_sharp, AA3)
    assign_twelve_edo_cell_intervals(f_flat, a_dblsharp, AAA3)
    assign_twelve_edo_cell_intervals(f_flat, b_dblflat, P4)
    assign_twelve_edo_cell_intervals(f_flat, b_nat, A4)
    assign_twelve_edo_cell_intervals(f_flat, b_nat, AA4)
    assign_twelve_edo_cell_intervals(f_flat, b_sharp, AAA4)
    assign_twelve_edo_cell_intervals(f_flat, b_dblsharp, AAAA4)
    assign_twelve_edo_cell_intervals(f_flat, c_dblflat, d5)
    assign_twelve_edo_cell_intervals(f_flat, c_flat, P5)
    assign_twelve_edo_cell_intervals(f_flat, c_nat, A5)
    assign_twelve_edo_cell_intervals(f_flat, c_sharp, AA5)
    assign_twelve_edo_cell_intervals(f_flat, c_dblsharp, AAA5)
    assign_twelve_edo_cell_intervals(f_flat, d_dblflat, m6)
    assign_twelve_edo_cell_intervals(f_flat, d_flat, M6)
    assign_twelve_edo_cell_intervals(f_flat, d_nat, A6)
    assign_twelve_edo_cell_intervals(f_flat, d_sharp, AA6)
    assign_twelve_edo_cell_intervals(f_flat, d_dblsharp, AAA6)
    assign_twelve_edo_cell_intervals(f_flat, e_dblflat, m7)
    assign_twelve_edo_cell_intervals(f_flat, e_flat, M7)
    assign_twelve_edo_cell_intervals(f_flat, e_nat, A7)
    assign_twelve_edo_cell_intervals(f_flat, e_sharp, AA7)
    assign_twelve_edo_cell_intervals(f_flat, e_dblsharp, AAA7)
    assign_twelve_edo_cell_intervals(f_flat, f_dblflat, d1)
    assign_twelve_edo_cell_intervals(f_nat, a_dblflat, d3)
    assign_twelve_edo_cell_intervals(f_nat, a_flat, m3)
    assign_twelve_edo_cell_intervals(f_nat, a_nat, M3)
    assign_twelve_edo_cell_intervals(f_nat, a_sharp, A3)
    assign_twelve_edo_cell_intervals(f_nat, a_dblsharp, AA3)
    assign_twelve_edo_cell_intervals(f_nat, b_dblflat, d4)
    assign_twelve_edo_cell_intervals(f_nat, b_nat, P4)
    assign_twelve_edo_cell_intervals(f_nat, b_nat, A4)
    assign_twelve_edo_cell_intervals(f_nat, b_sharp, AA4)
    assign_twelve_edo_cell_intervals(f_nat, b_dblsharp, AAA4)
    assign_twelve_edo_cell_intervals(f_nat, c_dblflat, dd5)
    assign_twelve_edo_cell_intervals(f_nat, c_flat, d5)
    assign_twelve_edo_cell_intervals(f_nat, c_nat, P5)
    assign_twelve_edo_cell_intervals(f_nat, c_sharp, A5)
    assign_twelve_edo_cell_intervals(f_nat, c_dblsharp, AA5)
    assign_twelve_edo_cell_intervals(f_nat, d_dblflat, d6)
    assign_twelve_edo_cell_intervals(f_nat, d_flat, m6)
    assign_twelve_edo_cell_intervals(f_nat, d_nat, M6)
    assign_twelve_edo_cell_intervals(f_nat, d_sharp, A6)
    assign_twelve_edo_cell_intervals(f_nat, d_dblsharp, AA6)
    assign_twelve_edo_cell_intervals(f_nat, e_dblflat, d7)
    assign_twelve_edo_cell_intervals(f_nat, e_flat, m7)
    assign_twelve_edo_cell_intervals(f_nat, e_nat, M7)
    assign_twelve_edo_cell_intervals(f_nat, e_sharp, A7)
    assign_twelve_edo_cell_intervals(f_nat, e_dblsharp, AA7)
    assign_twelve_edo_cell_intervals(f_nat, f_dblflat, dd1)
    assign_twelve_edo_cell_intervals(f_nat, f_flat, d1)
    assign_twelve_edo_cell_intervals(f_sharp, a_dblflat, dd3)
    assign_twelve_edo_cell_intervals(f_sharp, a_flat, d3)
    assign_twelve_edo_cell_intervals(f_sharp, a_nat, m3)
    assign_twelve_edo_cell_intervals(f_sharp, a_sharp, M3)
    assign_twelve_edo_cell_intervals(f_sharp, a_dblsharp, A3)
    assign_twelve_edo_cell_intervals(f_sharp, b_dblflat, dd4)
    assign_twelve_edo_cell_intervals(f_sharp, b_nat, d4)
    assign_twelve_edo_cell_intervals(f_sharp, b_nat, P4)
    assign_twelve_edo_cell_intervals(f_sharp, b_sharp, A4)
    assign_twelve_edo_cell_intervals(f_sharp, b_dblsharp, AA4)
    assign_twelve_edo_cell_intervals(f_sharp, c_dblflat, ddd5)
    assign_twelve_edo_cell_intervals(f_sharp, c_flat, dd5)
    assign_twelve_edo_cell_intervals(f_sharp, c_nat, d5)
    assign_twelve_edo_cell_intervals(f_sharp, c_sharp, P5)
    assign_twelve_edo_cell_intervals(f_sharp, c_dblsharp, A5)
    assign_twelve_edo_cell_intervals(f_sharp, d_dblflat, dd6)
    assign_twelve_edo_cell_intervals(f_sharp, d_flat, d6)
    assign_twelve_edo_cell_intervals(f_sharp, d_nat, m6)
    assign_twelve_edo_cell_intervals(f_sharp, d_sharp, M6)
    assign_twelve_edo_cell_intervals(f_sharp, d_dblsharp, A6)
    assign_twelve_edo_cell_intervals(f_sharp, e_dblflat, dd7)
    assign_twelve_edo_cell_intervals(f_sharp, e_flat, d7)
    assign_twelve_edo_cell_intervals(f_sharp, e_nat, m7)
    assign_twelve_edo_cell_intervals(f_sharp, e_sharp, M7)
    assign_twelve_edo_cell_intervals(f_sharp, e_dblsharp, A7)
    assign_twelve_edo_cell_intervals(f_sharp, f_dblflat, ddd1)
    assign_twelve_edo_cell_intervals(f_sharp, f_flat, dd1)
    assign_twelve_edo_cell_intervals(f_sharp, f_nat, d1)
    assign_twelve_edo_cell_intervals(f_dblsharp, a_dblflat, ddd3)
    assign_twelve_edo_cell_intervals(f_dblsharp, a_flat, dd3)
    assign_twelve_edo_cell_intervals(f_dblsharp, a_nat, d3)
    assign_twelve_edo_cell_intervals(f_dblsharp, a_sharp, m3)
    assign_twelve_edo_cell_intervals(f_dblsharp, a_dblsharp, M3)
    assign_twelve_edo_cell_intervals(f_dblsharp, b_dblflat, ddd4)
    assign_twelve_edo_cell_intervals(f_dblsharp, b_nat, dd4)
    assign_twelve_edo_cell_intervals(f_dblsharp, b_nat, d4)
    assign_twelve_edo_cell_intervals(f_dblsharp, b_sharp, P4)
    assign_twelve_edo_cell_intervals(f_dblsharp, b_dblsharp, A4)
    assign_twelve_edo_cell_intervals(f_dblsharp, c_dblflat, dddd5)
    assign_twelve_edo_cell_intervals(f_dblsharp, c_flat, ddd5)
    assign_twelve_edo_cell_intervals(f_dblsharp, c_nat, dd5)
    assign_twelve_edo_cell_intervals(f_dblsharp, c_sharp, d5)
    assign_twelve_edo_cell_intervals(f_dblsharp, c_dblsharp, P5)
    assign_twelve_edo_cell_intervals(f_dblsharp, d_dblflat, ddd6)
    assign_twelve_edo_cell_intervals(f_dblsharp, d_flat, dd6)
    assign_twelve_edo_cell_intervals(f_dblsharp, d_nat, d6)
    assign_twelve_edo_cell_intervals(f_dblsharp, d_sharp, m6)
    assign_twelve_edo_cell_intervals(f_dblsharp, d_dblsharp, M6)
    assign_twelve_edo_cell_intervals(f_dblsharp, e_dblflat, ddd7)
    assign_twelve_edo_cell_intervals(f_dblsharp, e_flat, dd7)
    assign_twelve_edo_cell_intervals(f_dblsharp, e_nat, d7)
    assign_twelve_edo_cell_intervals(f_dblsharp, e_sharp, m7)
    assign_twelve_edo_cell_intervals(f_dblsharp, e_dblsharp, M7)
    assign_twelve_edo_cell_intervals(f_dblsharp, f_dblflat, dddd1)
    assign_twelve_edo_cell_intervals(f_dblsharp, f_flat, ddd1)
    assign_twelve_edo_cell_intervals(f_dblsharp, f_nat, dd1)
    assign_twelve_edo_cell_intervals(f_dblsharp, f_sharp, d1)
    assign_twelve_edo_cell_intervals(g_dblflat, a_dblflat, M2)
    assign_twelve_edo_cell_intervals(g_dblflat, a_flat, A2)
    assign_twelve_edo_cell_intervals(g_dblflat, a_nat, AA2)
    assign_twelve_edo_cell_intervals(g_dblflat, a_sharp, AAA2)
    assign_twelve_edo_cell_intervals(g_dblflat, a_dblsharp, AAAA2)
    assign_twelve_edo_cell_intervals(g_dblflat, b_dblflat, M3)
    assign_twelve_edo_cell_intervals(g_dblflat, b_nat, A3)
    assign_twelve_edo_cell_intervals(g_dblflat, b_nat, AA3)
    assign_twelve_edo_cell_intervals(g_dblflat, b_sharp, AAA3)
    assign_twelve_edo_cell_intervals(g_dblflat, b_dblsharp, AAAA3)
    assign_twelve_edo_cell_intervals(g_dblflat, c_dblflat, P4)
    assign_twelve_edo_cell_intervals(g_dblflat, c_flat, A4)
    assign_twelve_edo_cell_intervals(g_dblflat, c_nat, AA4)
    assign_twelve_edo_cell_intervals(g_dblflat, c_sharp, AAA4)
    assign_twelve_edo_cell_intervals(g_dblflat, c_dblsharp, AAAA4)
    assign_twelve_edo_cell_intervals(g_dblflat, d_dblflat, P5)
    assign_twelve_edo_cell_intervals(g_dblflat, d_flat, A5)
    assign_twelve_edo_cell_intervals(g_dblflat, d_nat, AA5)
    assign_twelve_edo_cell_intervals(g_dblflat, d_sharp, AAA5)
    assign_twelve_edo_cell_intervals(g_dblflat, d_dblsharp, AAAA5)
    assign_twelve_edo_cell_intervals(g_dblflat, e_dblflat, M6)
    assign_twelve_edo_cell_intervals(g_dblflat, e_flat, A6)
    assign_twelve_edo_cell_intervals(g_dblflat, e_nat, AA6)
    assign_twelve_edo_cell_intervals(g_dblflat, e_sharp, AAA6)
    assign_twelve_edo_cell_intervals(g_dblflat, e_dblsharp, AAAA6)
    assign_twelve_edo_cell_intervals(g_dblflat, f_dblflat, M7)
    assign_twelve_edo_cell_intervals(g_dblflat, f_flat, A7)
    assign_twelve_edo_cell_intervals(g_dblflat, f_nat, AA7)
    assign_twelve_edo_cell_intervals(g_dblflat, f_sharp, AAA7)
    assign_twelve_edo_cell_intervals(g_dblflat, f_dblsharp, AAAA7)
    assign_twelve_edo_cell_intervals(g_flat, a_dblflat, m2)
    assign_twelve_edo_cell_intervals(g_flat, a_flat, A2)
    assign_twelve_edo_cell_intervals(g_flat, a_nat, AA2)
    assign_twelve_edo_cell_intervals(g_flat, a_sharp, AA2)
    assign_twelve_edo_cell_intervals(g_flat, a_dblsharp, AAA2)
    assign_twelve_edo_cell_intervals(g_flat, b_dblflat, m3)
    assign_twelve_edo_cell_intervals(g_flat, b_nat, M3)
    assign_twelve_edo_cell_intervals(g_flat, b_nat, A3)
    assign_twelve_edo_cell_intervals(g_flat, b_sharp, AA3)
    assign_twelve_edo_cell_intervals(g_flat, b_dblsharp, AAA3)
    assign_twelve_edo_cell_intervals(g_flat, c_dblflat, d4)
    assign_twelve_edo_cell_intervals(g_flat, c_flat, P4)
    assign_twelve_edo_cell_intervals(g_flat, c_nat, A4)
    assign_twelve_edo_cell_intervals(g_flat, c_sharp, AA4)
    assign_twelve_edo_cell_intervals(g_flat, c_dblsharp, AAA4)
    assign_twelve_edo_cell_intervals(g_flat, d_dblflat, d5)
    assign_twelve_edo_cell_intervals(g_flat, d_flat, P5)
    assign_twelve_edo_cell_intervals(g_flat, d_nat, A5)
    assign_twelve_edo_cell_intervals(g_flat, d_sharp, AA5)
    assign_twelve_edo_cell_intervals(g_flat, d_dblsharp, AAA5)
    assign_twelve_edo_cell_intervals(g_flat, e_dblflat, m6)
    assign_twelve_edo_cell_intervals(g_flat, e_flat, M6)
    assign_twelve_edo_cell_intervals(g_flat, e_nat, A6)
    assign_twelve_edo_cell_intervals(g_flat, e_sharp, AA6)
    assign_twelve_edo_cell_intervals(g_flat, e_dblsharp, AAA6)
    assign_twelve_edo_cell_intervals(g_flat, f_dblflat, m7)
    assign_twelve_edo_cell_intervals(g_flat, f_flat, M7)
    assign_twelve_edo_cell_intervals(g_flat, f_nat, A7)
    assign_twelve_edo_cell_intervals(g_flat, f_sharp, AA7)
    assign_twelve_edo_cell_intervals(g_flat, f_dblsharp, AAA7)
    assign_twelve_edo_cell_intervals(g_flat, g_dblflat, d1)
    assign_twelve_edo_cell_intervals(g_nat, a_dblflat, d2)
    assign_twelve_edo_cell_intervals(g_nat, a_flat, m2)
    assign_twelve_edo_cell_intervals(g_nat, a_nat, M2)
    assign_twelve_edo_cell_intervals(g_nat, a_sharp, A2)
    assign_twelve_edo_cell_intervals(g_nat, a_dblsharp, AA2)
    assign_twelve_edo_cell_intervals(g_nat, b_dblflat, d3)
    assign_twelve_edo_cell_intervals(g_nat, b_nat, m3)
    assign_twelve_edo_cell_intervals(g_nat, b_nat, M3)
    assign_twelve_edo_cell_intervals(g_nat, b_sharp, A3)
    assign_twelve_edo_cell_intervals(g_nat, b_dblsharp, AA3)
    assign_twelve_edo_cell_intervals(g_nat, c_dblflat, dd4)
    assign_twelve_edo_cell_intervals(g_nat, c_flat, d4)
    assign_twelve_edo_cell_intervals(g_nat, c_nat, P4)
    assign_twelve_edo_cell_intervals(g_nat, c_sharp, A4)
    assign_twelve_edo_cell_intervals(g_nat, c_dblsharp, AA4)
    assign_twelve_edo_cell_intervals(g_nat, d_dblflat, dd5)
    assign_twelve_edo_cell_intervals(g_nat, d_flat, d5)
    assign_twelve_edo_cell_intervals(g_nat, d_nat, P5)
    assign_twelve_edo_cell_intervals(g_nat, d_sharp, A5)
    assign_twelve_edo_cell_intervals(g_nat, d_dblsharp, AA5)
    assign_twelve_edo_cell_intervals(g_nat, e_dblflat, d6)
    assign_twelve_edo_cell_intervals(g_nat, e_flat, m6)
    assign_twelve_edo_cell_intervals(g_nat, e_nat, M6)
    assign_twelve_edo_cell_intervals(g_nat, e_sharp, A6)
    assign_twelve_edo_cell_intervals(g_nat, e_dblsharp, AA6)
    assign_twelve_edo_cell_intervals(g_nat, f_dblflat, d7)
    assign_twelve_edo_cell_intervals(g_nat, f_flat, m7)
    assign_twelve_edo_cell_intervals(g_nat, f_nat, M7)
    assign_twelve_edo_cell_intervals(g_nat, f_sharp, A7)
    assign_twelve_edo_cell_intervals(g_nat, f_dblsharp, AA7)
    assign_twelve_edo_cell_intervals(g_nat, g_dblflat, dd1)
    assign_twelve_edo_cell_intervals(g_nat, g_flat, d1)
    assign_twelve_edo_cell_intervals(g_sharp, a_dblflat, dd2)
    assign_twelve_edo_cell_intervals(g_sharp, a_flat, d2)
    assign_twelve_edo_cell_intervals(g_sharp, a_nat, m2)
    assign_twelve_edo_cell_intervals(g_sharp, a_sharp, M2)
    assign_twelve_edo_cell_intervals(g_sharp, a_dblsharp, A2)
    assign_twelve_edo_cell_intervals(g_sharp, b_dblflat, dd3)
    assign_twelve_edo_cell_intervals(g_sharp, b_nat, d3)
    assign_twelve_edo_cell_intervals(g_sharp, b_nat, m3)
    assign_twelve_edo_cell_intervals(g_sharp, b_sharp, M3)
    assign_twelve_edo_cell_intervals(g_sharp, b_dblsharp, A3)
    assign_twelve_edo_cell_intervals(g_sharp, c_dblflat, ddd4)
    assign_twelve_edo_cell_intervals(g_sharp, c_flat, ddd4)
    assign_twelve_edo_cell_intervals(g_sharp, c_nat, dd4)
    assign_twelve_edo_cell_intervals(g_sharp, c_sharp, P4)
    assign_twelve_edo_cell_intervals(g_sharp, c_dblsharp, A4)
    assign_twelve_edo_cell_intervals(g_sharp, d_dblflat, ddd5)
    assign_twelve_edo_cell_intervals(g_sharp, d_flat, dd5)
    assign_twelve_edo_cell_intervals(g_sharp, d_nat, d5)
    assign_twelve_edo_cell_intervals(g_sharp, d_sharp, P5)
    assign_twelve_edo_cell_intervals(g_sharp, d_dblsharp, A5)
    assign_twelve_edo_cell_intervals(g_sharp, e_dblflat, dd6)
    assign_twelve_edo_cell_intervals(g_sharp, e_flat, d6)
    assign_twelve_edo_cell_intervals(g_sharp, e_nat, m6)
    assign_twelve_edo_cell_intervals(g_sharp, e_sharp, M6)
    assign_twelve_edo_cell_intervals(g_sharp, e_dblsharp, A6)
    assign_twelve_edo_cell_intervals(g_sharp, f_dblflat, dd7)
    assign_twelve_edo_cell_intervals(g_sharp, f_flat, d7)
    assign_twelve_edo_cell_intervals(g_sharp, f_nat, m7)
    assign_twelve_edo_cell_intervals(g_sharp, f_sharp, M7)
    assign_twelve_edo_cell_intervals(g_sharp, f_dblsharp, A7)
    assign_twelve_edo_cell_intervals(g_sharp, g_dblflat, ddd1)
    assign_twelve_edo_cell_intervals(g_sharp, g_flat, dd1)
    assign_twelve_edo_cell_intervals(g_sharp, g_nat, d1)
    assign_twelve_edo_cell_intervals(g_dblsharp, a_dblflat, ddd2)
    assign_twelve_edo_cell_intervals(g_dblsharp, a_flat, dd2)
    assign_twelve_edo_cell_intervals(g_dblsharp, a_nat, d2)
    assign_twelve_edo_cell_intervals(g_dblsharp, a_sharp, m2)
    assign_twelve_edo_cell_intervals(g_dblsharp, a_dblsharp, M2)
    assign_twelve_edo_cell_intervals(g_dblsharp, b_dblflat, ddd3)
    assign_twelve_edo_cell_intervals(g_dblsharp, b_nat, dd3)
    assign_twelve_edo_cell_intervals(g_dblsharp, b_nat, d3)
    assign_twelve_edo_cell_intervals(g_dblsharp, b_sharp, m3)
    assign_twelve_edo_cell_intervals(g_dblsharp, b_dblsharp, M3)
    assign_twelve_edo_cell_intervals(g_dblsharp, c_dblflat, dddd4)
    assign_twelve_edo_cell_intervals(g_dblsharp, c_flat, ddd4)
    assign_twelve_edo_cell_intervals(g_dblsharp, c_nat, dd4)
    assign_twelve_edo_cell_intervals(g_dblsharp, c_sharp, d4)
    assign_twelve_edo_cell_intervals(g_dblsharp, c_dblsharp, P4)
    assign_twelve_edo_cell_intervals(g_dblsharp, d_dblflat, dddd5)
    assign_twelve_edo_cell_intervals(g_dblsharp, d_flat, ddd5)
    assign_twelve_edo_cell_intervals(g_dblsharp, d_nat, dd5)
    assign_twelve_edo_cell_intervals(g_dblsharp, d_sharp, d5)
    assign_twelve_edo_cell_intervals(g_dblsharp, d_dblsharp, P5)
    assign_twelve_edo_cell_intervals(g_dblsharp, e_dblflat, ddd6)
    assign_twelve_edo_cell_intervals(g_dblsharp, e_flat, dd6)
    assign_twelve_edo_cell_intervals(g_dblsharp, e_nat, d6)
    assign_twelve_edo_cell_intervals(g_dblsharp, e_sharp, m6)
    assign_twelve_edo_cell_intervals(g_dblsharp, e_dblsharp, M6)
    assign_twelve_edo_cell_intervals(g_dblsharp, f_dblflat, ddd7)
    assign_twelve_edo_cell_intervals(g_dblsharp, f_flat, dd7)
    assign_twelve_edo_cell_intervals(g_dblsharp, f_nat, d7)
    assign_twelve_edo_cell_intervals(g_dblsharp, f_sharp, m7)
    assign_twelve_edo_cell_intervals(g_dblsharp, f_dblsharp, M7)
    assign_twelve_edo_cell_intervals(g_dblsharp, g_dblflat, dddd1)
    assign_twelve_edo_cell_intervals(g_dblsharp, g_flat, ddd1)
    assign_twelve_edo_cell_intervals(g_dblsharp, g_nat, dd1)
    assign_twelve_edo_cell_intervals(g_dblsharp, g_sharp, d1)
    # END OF METAPROGRAMMING

    cell_1 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=1)
    cell_2 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=2)
    cell_3 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=3)
    cell_4 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=4)
    cell_5 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=5)
    cell_6 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=6)
    cell_7 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=7)
    cell_8 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=8)
    cell_9 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=9)
    cell_10 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=10)
    cell_11 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=11)
    cell_12 = make(Enharmonic, tuning_system=twelve_edo, chromatic_number=12)

    # cell_1: A Cell
    enh(cell_1, a_nat)
    enh(cell_1, b_dblflat)
    enh(cell_1, g_dblsharp)

    # cell_2: A# Cell
    enh(cell_2, b_flat)
    enh(cell_2, a_sharp)
    enh(cell_2, c_dblflat)

    # cell_3: B Cell
    enh(cell_3, c_flat)
    enh(cell_3, b_nat)
    enh(cell_3, a_dblsharp)

    # cell_4: C Cell
    enh(cell_4, d_dblflat)
    enh(cell_4, c_nat)
    enh(cell_4, b_sharp)

    # cell_5: C# Cell
    enh(cell_5, d_flat)
    enh(cell_5, c_sharp)
    enh(cell_5, b_dblsharp)

    # cell_6: D Cell
    enh(cell_6, e_dblflat)
    enh(cell_6, d_nat)
    enh(cell_6, c_dblsharp)

    # cell_7: D# Cell
    enh(cell_7, f_dblflat)
    enh(cell_7, e_flat)
    enh(cell_7, d_sharp)

    # cell_8: E Cell
    enh(cell_8, f_flat)
    enh(cell_8, e_nat)
    enh(cell_8, d_dblsharp)

    # cell_9: F Cell
    enh(cell_9, g_dblflat)
    enh(cell_9, f_nat)
    enh(cell_9, e_sharp)

    # cell_10: F# Cell
    enh(cell_10, g_flat)
    enh(cell_10, f_sharp)
    enh(cell_10, e_dblsharp)

    # cell_11: G Cell
    enh(cell_11, a_dblflat)
    enh(cell_11, g_nat)
    enh(cell_11, f_dblsharp)

    # cell_12: G# Cell
    enh(cell_12, g_sharp)
    enh(cell_12, a_flat)


def safe_seed():
    try:
        prime = Administrarion.objects.get(username='Prime')
    except Exception as e:
        prime = Administrarion(username='Prime')
        prime.save()
    
    do_seed(prime)


class Command(BaseCommand):
    help = "Closes the specified poll for voting"

    def add_arguments(self, parser):
        pass

    def handle(self, *args, **options):
        safe_seed()