# Generated by Django 5.0.7 on 2024-09-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politeum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstleveldivision',
            name='abbreviation',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
