# Generated by Django 5.0.7 on 2024-09-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarium', '0003_ontologicalrelationtype_ontologion_and_more'),
        ('politeum', '0002_firstleveldivision_abbreviation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeCountryName',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('other_name', models.CharField(max_length=200)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='CulturalArtifactMetaLink',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='CulturalArtifactOntology',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='CulturalArtifactTypeMetaField',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.RemoveField(
            model_name='culturalartifactmetatype',
            name='meta_kind',
        ),
        migrations.RemoveField(
            model_name='culturalartifactmetatype',
            name='pragmon_ptr',
        ),
        migrations.RemoveField(
            model_name='culturalartifactreview',
            name='artifact',
        ),
        migrations.RemoveField(
            model_name='culturalartifactreview',
            name='pragmon_ptr',
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_country_name'),
        ),
        migrations.AddField(
            model_name='alternativecountryname',
            name='relative_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='politeum.country'),
        ),
        migrations.AddField(
            model_name='culturalartifactmetalink',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='politeum.culturalartifacttype'),
        ),
        migrations.AddField(
            model_name='culturalartifactontology',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='politeum.culturalartifact'),
        ),
        migrations.AddField(
            model_name='culturalartifactontology',
            name='relevant_ontologion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrarium.ontologion'),
        ),
        migrations.AddField(
            model_name='culturalartifactmetalink',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='politeum.culturalartifacttypemetafield'),
        ),
        migrations.AlterField(
            model_name='culturalartifactmeta',
            name='meta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='politeum.culturalartifacttypemetafield'),
        ),
        migrations.DeleteModel(
            name='CulturalArtifactReview',
        ),
        migrations.DeleteModel(
            name='CulturalArtifactMetaType',
        ),
    ]
