# Generated by Django 5.0.7 on 2024-09-19 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrarium', '0004_pragmon_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalModel',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('species', models.CharField(max_length=255, unique=True)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='IdentificationSystem',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('smiles', models.TextField(unique=True)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='MoleculeNamingSystem',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='MoleculeName',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=255)),
                ('relative_molecule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='named_molecule', to='pharmakeium.molecule')),
                ('naming_system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmakeium.moleculenamingsystem')),
            ],
            options={
                'unique_together': {('relative_molecule', 'naming_system')},
            },
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=255)),
                ('unigene', models.CharField(max_length=50, unique=True)),
                ('source', models.CharField(max_length=255)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmakeium.animalmodel')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='kiDbBindingAffinity',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('number', models.IntegerField()),
                ('ki_note', models.TextField(blank=True, null=True)),
                ('ki_val', models.FloatField()),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('hotligand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='hotligand_affinities', to='pharmakeium.moleculename')),
                ('ligand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ligand_affinities', to='pharmakeium.moleculename')),
                ('relative_receptor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmakeium.receptor')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('identifier', models.CharField(max_length=255)),
                ('identification_system', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='pharmakeium.identificationsystem')),
                ('relative_molecule', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='identified_molecule', to='pharmakeium.molecule')),
            ],
            options={
                'unique_together': {('relative_molecule', 'identification_system')},
            },
            bases=('administrarium.pragmon',),
        ),
    ]
