# Generated by Django 5.0.7 on 2024-08-15 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarium', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pragmon',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
