# Generated by Django 5.0.7 on 2024-09-16 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarium', '0002_alter_pragmon_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologicalRelationType',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='Ontologion',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=50)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='OntologicalRelation',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrarium.ontologicalrelationtype')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='source', to='administrarium.ontologion')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='administrarium.ontologion')),
            ],
            bases=('administrarium.pragmon',),
        ),
    ]
