# Generated by Django 5.0.7 on 2024-09-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarium', '0003_ontologicalrelationtype_ontologion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pragmon',
            name='is_active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ontologicalrelation',
            unique_together={('source', 'target', 'kind')},
        ),
    ]
