# Generated by Django 5.0.7 on 2024-08-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harmonium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interval',
            name='symbol',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervalquality',
            name='symbol',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
    ]
