# Generated by Django 5.0.7 on 2024-09-09 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrarium', '0002_alter_pragmon_id'),
        ('harmonium', '0003_accidentaldirection_accidental_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleFamily',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=30)),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.RemoveField(
            model_name='interval',
            name='denominator_mod',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='numerator_mod',
        ),
        migrations.RemoveField(
            model_name='interval',
            name='step_mod',
        ),
        migrations.CreateModel(
            name='EnharmonicIntervalAssignment',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('first_note', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='first_note', to='harmonium.note')),
                ('relative_interval', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='harmonium.interval')),
                ('relative_tuning', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='harmonium.tuningsystem')),
                ('second_note', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='second_note', to='harmonium.note')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='EquivarationalRelation',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=100)),
                ('relative_tuning', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='harmonium.tuningsystem')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='IntervalInverse',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('first_interval', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='first_interval', to='harmonium.interval')),
                ('second_interval', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='second_interval', to='harmonium.interval')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='ScaleStep',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('name', models.CharField(max_length=30)),
                ('symbol', models.CharField(max_length=30)),
                ('relative_interval', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='harmonium.interval')),
            ],
            bases=('administrarium.pragmon',),
        ),
        migrations.CreateModel(
            name='ScaleDegree',
            fields=[
                ('pragmon_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administrarium.pragmon')),
                ('mode_name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('relative_step', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='harmonium.scalestep')),
            ],
            bases=('administrarium.pragmon',),
        ),
    ]
