# Generated by Django 5.0.7 on 2024-09-09 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harmonium', '0004_scalefamily_remove_interval_denominator_mod_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equave',
            name='ratio',
        ),
        migrations.RemoveField(
            model_name='temperament',
            name='has_ratio_basis',
        ),
        migrations.RemoveField(
            model_name='temperament',
            name='has_step_basis',
        ),
    ]
